a = input('digite algo:')
print('o tipo primitivo desse valor e ',type(a))
print('so tem espaços ?', a.isspace())
print('e numerico ?', a.isnumeric())
print('ta capitalizado?',a.istitle())
print('e alfabetico?',a.isalpha())
print('e alpha numerico?',a.isalnum())
print('e decimal?',a.isdecimal())
print('ta maiuscula?',a.isupper())
print('ta minuscula',a.islower())
